# Re-eval commands to add exact_memorization to best/ saved models.
# Requires: configs/eval/tofu.yaml has exact_memorization enabled.

# tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.8 — step 100
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget01 holdout_split=holdout01 model=Llama-3.2-1B-Instruct task_name=tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.8 model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.8/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.8/checkpoint-100/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-1B-Instruct_retain99/TOFU_EVAL.json
# tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.8_sweep — step 100
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget01 holdout_split=holdout01 model=Llama-3.2-1B-Instruct task_name=tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.8_sweep model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.8_sweep/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.8_sweep/checkpoint-100/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-1B-Instruct_retain99/TOFU_EVAL.json
# tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.9 — step 10
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget01 holdout_split=holdout01 model=Llama-3.2-1B-Instruct task_name=tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.9 model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.9/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget01_LatentRMU_v4.9/checkpoint-10/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-1B-Instruct_retain99/TOFU_EVAL.json
# tofu_Llama-3.2-1B-Instruct_forget05_LatentRMU_v4.8 — step 125
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget05 holdout_split=holdout05 model=Llama-3.2-1B-Instruct task_name=tofu_Llama-3.2-1B-Instruct_forget05_LatentRMU_v4.8 model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget05_LatentRMU_v4.8/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget05_LatentRMU_v4.8/checkpoint-125/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-1B-Instruct_retain95/TOFU_EVAL.json
# tofu_Llama-3.2-1B-Instruct_forget05_LatentRMU_v4.8_sweep — step 125
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget05 holdout_split=holdout05 model=Llama-3.2-1B-Instruct task_name=tofu_Llama-3.2-1B-Instruct_forget05_LatentRMU_v4.8_sweep model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget05_LatentRMU_v4.8_sweep/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget05_LatentRMU_v4.8_sweep/checkpoint-125/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-1B-Instruct_retain95/TOFU_EVAL.json
# tofu_Llama-3.2-1B-Instruct_forget10_LatentRMU_v4.8 — step 150
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget10 holdout_split=holdout10 model=Llama-3.2-1B-Instruct task_name=tofu_Llama-3.2-1B-Instruct_forget10_LatentRMU_v4.8 model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget10_LatentRMU_v4.8/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget10_LatentRMU_v4.8/checkpoint-150/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-1B-Instruct_retain90/TOFU_EVAL.json
# tofu_Llama-3.2-1B-Instruct_forget10_LatentRMU_v4.8_sweep — step 150
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget10 holdout_split=holdout10 model=Llama-3.2-1B-Instruct task_name=tofu_Llama-3.2-1B-Instruct_forget10_LatentRMU_v4.8_sweep model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget10_LatentRMU_v4.8_sweep/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-1B-Instruct_forget10_LatentRMU_v4.8_sweep/checkpoint-150/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-1B-Instruct_retain90/TOFU_EVAL.json
# tofu_Llama-3.2-3B-Instruct_forget01_LatentRMU_v4.8 — step 50
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget01 holdout_split=holdout01 model=Llama-3.2-3B-Instruct task_name=tofu_Llama-3.2-3B-Instruct_forget01_LatentRMU_v4.8 model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget01_LatentRMU_v4.8/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget01_LatentRMU_v4.8/checkpoint-50/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-3B-Instruct_retain99/TOFU_EVAL.json
# tofu_Llama-3.2-3B-Instruct_forget01_LatentRMU_v4.8_sweep — step 40
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget01 holdout_split=holdout01 model=Llama-3.2-3B-Instruct task_name=tofu_Llama-3.2-3B-Instruct_forget01_LatentRMU_v4.8_sweep model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget01_LatentRMU_v4.8_sweep/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget01_LatentRMU_v4.8_sweep/checkpoint-40/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-3B-Instruct_retain99/TOFU_EVAL.json
# tofu_Llama-3.2-3B-Instruct_forget05_LatentRMU_v4.8 — step 75
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget05 holdout_split=holdout05 model=Llama-3.2-3B-Instruct task_name=tofu_Llama-3.2-3B-Instruct_forget05_LatentRMU_v4.8 model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget05_LatentRMU_v4.8/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget05_LatentRMU_v4.8/checkpoint-75/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-3B-Instruct_retain95/TOFU_EVAL.json
# tofu_Llama-3.2-3B-Instruct_forget05_LatentRMU_v4.8_sweep — step 75
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget05 holdout_split=holdout05 model=Llama-3.2-3B-Instruct task_name=tofu_Llama-3.2-3B-Instruct_forget05_LatentRMU_v4.8_sweep model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget05_LatentRMU_v4.8_sweep/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget05_LatentRMU_v4.8_sweep/checkpoint-75/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-3B-Instruct_retain95/TOFU_EVAL.json
# tofu_Llama-3.2-3B-Instruct_forget10_LatentRMU_v4.8 — step 100
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget10 holdout_split=holdout10 model=Llama-3.2-3B-Instruct task_name=tofu_Llama-3.2-3B-Instruct_forget10_LatentRMU_v4.8 model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget10_LatentRMU_v4.8/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget10_LatentRMU_v4.8/checkpoint-100/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-3B-Instruct_retain90/TOFU_EVAL.json
# tofu_Llama-3.2-3B-Instruct_forget10_LatentRMU_v4.8_sweep — step 100
CUDA_VISIBLE_DEVICES=0 python src/eval.py --config-name=eval.yaml experiment=eval/tofu/default forget_split=forget10 holdout_split=holdout10 model=Llama-3.2-3B-Instruct task_name=tofu_Llama-3.2-3B-Instruct_forget10_LatentRMU_v4.8_sweep model.model_args.pretrained_model_name_or_path=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget10_LatentRMU_v4.8_sweep/best paths.output_dir=saves/unlearn/tofu_Llama-3.2-3B-Instruct_forget10_LatentRMU_v4.8_sweep/checkpoint-100/evals eval.tofu.overwrite=true retain_logs_path=saves/eval/tofu_Llama-3.2-3B-Instruct_retain90/TOFU_EVAL.json

